name: deploy

on: [deployment]

jobs:
  tests:
    name: deploy on github
    runs-on: macos-latest
    env:
      GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby 2.6.x
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x

      - name: Install bundler
        run: |
          gem install bundler:2.0.2

      - name: create packages
        run: |
          bundle install
          bundle exec rake package_all

      - name: Install hub
        run: brew install hub
      - name: update
        run: |
          cd deploy
          if [ -z "$version" ]; then
            version=$(ls gauge-ruby* | head -1 | sed "s/\.[^\.]*$//" | sed "s/gauge-ruby-//" | sed "s/-[a-z]*\.[a-z0-9_]*$//");
          fi
          artifacts=()
          dir=`pwd`
          for i in `ls`; do
              artifacts+="$dir/$i "
          done
          cd ..
          echo "---------------------------"
          echo "Updating release v$version"
          echo "---------------------------"
          echo -e "Gauge Ruby v$version\n\n" > desc.txt
          release_description=$(ruby -e "$(curl -sSfL https://github.com/getgauge/gauge/raw/master/build/create_release_text.rb)" gauge-ruby getgauge)
          echo "$release_description" >> desc.txt
          echo "Creating new draft for release v$version"
          hub release create -d -F ./desc.txt "v$version"
          rm -rf desc.txt
          echo "Start uploading assets..."
          for i in `ls $artifacts`; do
              hub release edit -m "" -a $i "v$version"
              if [ $? -ne 0 ];then
                  exit 1
              fi
          done
      - name: 'deployment success'
        if: success()
        uses: 'deliverybot/status@master'
        with:
          state: 'success'
          token: '${{ secrets.GITHUB_TOKEN }}'

      - name: 'deployment failure'
        if: failure()
        uses: 'deliverybot/status@master'
        with:
          state: 'failure'
          token: '${{ secrets.GITHUB_TOKEN }}'
